### ISSUE TITLE
Check number of cores in OSX

### ISSUE THREAD

**Issue by tammojan** [lofar-astron/lofar-deploy#18]
Should be `sysctl -n hw.ncpu` instead of `cat /proc/cpuinfo | grep processor | wc -l`. Not sure how to check for osx to make it a generic command.

**Comment by tammojan** [comment]
Anyone?

**Comment by ygrange** [comment]
That command returns the number of threads I have in OSX (It actually surprised me that I actually had 8 cores). 
Is that command indeed working on all Linuxes? Then we can just replace it.

**Comment by tammojan** [comment]
No, it does not work on all cpus. That's why I'm asking you, I was hoping you'd have the Make skills to do an if statement :)

**Comment by ygrange** [comment]
Ah I finally get what you mean by " Not sure how to check for osx"! Ok, that is something I can try to find out.

**Comment by ygrange** [comment]
For reference: https://stackoverflow.com/questions/714100/os-detecting-makefile
