### ISSUE TITLE
Install AOFlagger as dependency

### ISSUE THREAD

**Issue by tammojan** [lofar-astron/lofar-deploy#20]
In the upcoming release, AOFlagger is no longer part of the lofar repository but an external dependency (to be specified with -DAOFLAGGER_ROOT_DIR). It can be installed from https://sourceforge.net/projects/aoflagger/

**Comment by ygrange** [comment]
Hmm, this requires an extra bit of make magic to make sure we don't break previous releases. 

@tammojan Does the current trunk already work like this (i.e. do we have anything to test with)?
@bramveenboer any ideas how to tackle this? 

The easiest way to do it is to basically add lines that start with checking for the existance of a variable. The only issue with this scenario is that this will create several FS layers with virtually no change in the old releases (and an install script with a few lines that just don't execute. 

Whatever we do I propose to do it via a pull request and have someone do a bit of code review.

**Comment by bramveenboer** [comment]
I don't think that adding an additional -DAOFLAGGER_ROOT_DIR to the cmake configuration of LOFAR brakes releases or trunk versions that still include the AOFlagger. This variable is set in cmake, but just not used. (This is something that we can check easily btw.)

I don't think that we should invent a complex solution and instead just accept the fact the image will be (slightly) larger with this AOFlagger. I might not be used to compile the LOFAR software (for old releases), but might still prove useful for some users of this deploy mechanism.

**Comment by tammojan** [comment]
Agreed, it shouldn't break anything. 

Tammo Jan

**Comment by bramveenboer** [comment]
Done. See commit e17109c.

**Comment by tammojan** [comment]
I just found out that the external dependency was deferred to the following release (beginning 2016). But we're now prepared..
