### ISSUE TITLE
Everything broken on MAC

### ISSUE THREAD

**Issue by tammojan** [lofar-astron/lofar-deploy#23]
Aaaargh!

```
macdijkema:lofar-deploy dijkema$ make
head: illegal byte count -- -1
head: illegal byte count -- -1
head: illegal byte count -- -1
```

**Comment by ygrange** [comment]
This needs some testing but it looks like the behaviour can be mimicked by:

tmp_var=$(pwd | tr "//" "\n" | tail -n 2 | tr "\n" "-" )
echo ${tmp_var} | head -c $(echo `echo ${tmp_var} | wc -c ` -1 | bc )

It works on both OSX and Linux. I will change it and do a pull request. I am not very eager to just change it so if @bramveenboer wants to review the solution and pull in the request, that'd be great
