### ISSUE TITLE
wcslib-5.15.tar.bz2 missing

### ISSUE THREAD

**Issue by nzasch** [lofar-astron/lofar-deploy#27]
Hi
wcslib-5.15.tar.bz2 has been removed from ftp://ftp.atnf.csiro.au/pub/software/wcslib/
so, the installer fails

thanks
f

**Comment by apmechev** [comment]
try 
http://www.astro-wise.org/losoft/wcslib-5.15.tar.bz2

**Comment by ygrange** [comment]
Thanks for reporting. The people behind WCSLIB have a tendency of keeping a very limited number of versions online which breaks pretty much any build script. I'll update the URL by the one provided by @apmechev (thanks!).

**Comment by ygrange** [comment]
Should have been fixed by commit https://github.com/lofar-astron/lofar-deploy/commit/104cfbf5b1c5304d78ad08158231568dd911d427

**Comment by ygrange** [comment]
@nzasch Could you confirm this fixes the issue? Then I can safely close it.

**Comment by nzasch** [comment]
works well, now
thanks!
